import { ThemeOptions } from '@mui/material/styles/createTheme'


// According to MUI, module augemtation is required with TypeScript when creating custom variables in the theme
// MUI docs: https://mui.com/material-ui/customization/theming/#custom-variables
// Youtube tutorial: https://www.youtube.com/watch?v=ZyQlpX7lCRE

declare module '@mui/material/styles' {
	interface Theme {
		materialDesign: {
			primary: string
			primaryContainer: string
			onPrimary: string
			onPrimaryContainer: string
			secondary: string
			secondaryContainer: string
			onSecondary: string
			onSecondaryContainer: string
			tertiary: string
			tertiaryContainer: string
			onTertiary: string
			onTertiaryContainer: string
			error: string
			errorContainer: string
			onError: string
			onErrorContainer: string
			outline: string
			background: string
			onBackground: string
			surface: string
			onSurface: string
			surfaceVariant: string
			onSurfaceVariant: string
			inverseSurface: string
			inverseOnSurface: string
			inversePrimary: string
			shadow: string
			surfaceTint: string
			outlineVariant: string
			scrim: string,
            tones: {
                primary: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
                secondary: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
                tertiary: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
                error: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
                neutral: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
                neutralVariant: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
            }
		}
		tones: {
			primary: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
			secondary: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
			tertiary: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
			error: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
			neutral: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
			neutralVariant: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
		}
	}
	// allow configuration using `createTheme`
	interface ThemeOptions {
		materialDesign: {
			primary: string
			primaryContainer: string
			onPrimary: string
			onPrimaryContainer: string
			secondary: string
			secondaryContainer: string
			onSecondary: string
			onSecondaryContainer: string
			tertiary: string
			tertiaryContainer: string
			onTertiary: string
			onTertiaryContainer: string
			error: string
			errorContainer: string
			onError: string
			onErrorContainer: string
			outline: string
			background: string
			onBackground: string
			surface: string
			onSurface: string
			surfaceVariant: string
			onSurfaceVariant: string
			inverseSurface: string
			inverseOnSurface: string
			inversePrimary: string
			shadow: string
			surfaceTint: string
			outlineVariant: string
			scrim: string,
            tones: {
                primary: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
                secondary: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
                tertiary: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
                error: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
                neutral: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
                neutralVariant: {
                    0: string
                    5: string
                    10: string
                    15: string
                    20: string
                    25: string
                    30: string
                    35: string
                    40: string
                    50: string
                    60: string
                    70: string
                    80: string
                    90: string
                    95: string
                    98: string
                    99: string
                    100: string
                }
            }
		}
		tones: {
			primary: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
			secondary: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
			tertiary: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
			error: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
			neutral: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
			neutralVariant: {
				0: string
				5: string
				10: string
				15: string
				20: string
				25: string
				30: string
				35: string
				40: string
				50: string
				60: string
				70: string
				80: string
				90: string
				95: string
				98: string
				99: string
				100: string
			}
		}
	}
}
